### ISSUE TITLE
Crashes VS2019 nearly all the times

### ISSUE THREAD

**Issue by ebrouen** [wmjordan/Codist#138]
Hi,
I love this extension but unfortunately, it crashes VS 2019 (16.7.6 but also the previous versions) very often. Environement is Windows 10 FR Pro, VS2019 EN Ultimate, 32 Gb RAM.
If I disable the extension, problem disappears.
Is there any chance to get some log or indication about the origin of the issue?

**Comment by wmjordan** [comment]
Oh, sorry to hear that.


Please open the windows Event Viewer where may have some information about the crash. Just look for the `.NET Runtime` Error entries after the crash like the following screen shot. In the description part of the entry, there will be a stack trace. Post them here once you find it.

![image](https://user-images.githubusercontent.com/12182730/97542022-07052800-1a01-11eb-9185-88a38dfe66e3.png)

**Comment by ebrouen** [comment]
Thanks for the support.

Here is the event:

##
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at DynamicClass.GetAssemblySourceType(Microsoft.CodeAnalysis.IAssemblySymbol)
   at Codist.CodeAnalysisHelper+AssemblySourceReflector.GetSourceType(Microsoft.CodeAnalysis.IAssemblySymbol)
   at Codist.Margins.CSharpMembersMargin+SymbolReferenceMarker.Render(System.Windows.Media.DrawingContext)
   at Codist.Margins.CSharpMembersMargin.OnRender(System.Windows.Media.DrawingContext)
   at System.Windows.UIElement.Arrange(System.Windows.Rect)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(System.Object)
   at System.Windows.Media.MediaContext+InvokeOnRenderCallback.DoWork()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
##

**Comment by wmjordan** [comment]
Thank you for your efforts.

It may have something to do with the assemblies that your project references.
Codist uses reflection to detect whether a symbol in your code is from your source code or an imported assembly. That part has gotten some problem and caused the crash on your side.

I will investigate it and turn to you later.

**Comment by wmjordan** [comment]
Please try this version and see whether it works.
[Codist.zip](https://github.com/wmjordan/Codist/files/5457565/Codist.zip)

**Comment by ebrouen** [comment]
Good job!
After more than 20 hours of work, there was no crash at all. A very good new!
I close the issue. Thanks.

**Comment by wmjordan** [comment]
Good to hear that.
Thank you for your feedback!
