### ISSUE TITLE
[BUG] shortcut sometimes not working

### ISSUE THREAD

**Issue by fantasyz** [wmjordan/Codist#146]
Hi 
The shortcut to bring out the Search Declaration or Search Class Member sometimes not working for random file. However, clicking on the NaviBar will still bring out the drop down.  If I restart visual studio, the issue will be gone for a while but it will reappear after some coding. 

I tried put my cursor on different locations but it still doesn't work. e.g. inside/outside a function, etc. 

![DoqFq9op6S](https://user-images.githubusercontent.com/3223242/107112052-a99a3600-688f-11eb-9e0d-029945156389.jpg)

**Comment by wmjordan** [comment]
Bug confirmed.

**Comment by wmjordan** [comment]
Please try the new beta and see whether it works.

**Comment by fantasyz** [comment]
Tried the new beta, While the bug seems to be fixed. It crash very often and I currently have no idea what I did to crash it.

![Codist Error ](https://user-images.githubusercontent.com/3223242/107118354-8be2c600-68bb-11eb-94e3-ac1602cb620f.png)

**Comment by fantasyz** [comment]
The 1st crash happen after I added a new file to the project but I am not 100% sure it is related.

**Comment by wmjordan** [comment]
It might be another bug.

Could you take a look at the Windows Event Logs? There maybe some stack trace info.

**Comment by fantasyz** [comment]
Here is the stacktrace:

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.Collections.Hashtable.Insert(System.Object, System.Object, Boolean)
   at System.Collections.Hashtable.Add(System.Object, System.Object)
   at System.Collections.Specialized.HybridDictionary.Add(System.Object, System.Object)
   at Microsoft.VisualStudio.Utilities.PropertyCollection.AddProperty(System.Object, System.Object)
   at Codist.NaviBar.NaviBar..ctor(Microsoft.VisualStudio.Text.Editor.IWpfTextView)
   at Codist.NaviBar.CSharpBar..ctor(Microsoft.VisualStudio.Text.Editor.IWpfTextView)
   at Codist.NaviBar.NaviBarFactory+Overrider.FindNaviBar(System.Object, System.Windows.RoutedEventArgs)
   at Codist.NaviBar.NaviBarFactory+Overrider+<ResurrectNaviBar_OnUnloaded>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by wmjordan** [comment]
Please try the newer beta again.

**Comment by fantasyz** [comment]
The crash is still happening.  My visual studio is setup to use 3 cells split-view. It crash when I was trying move a tab in the middle cell to the left cell.

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.Collections.Hashtable.Insert(System.Object, System.Object, Boolean)
   at System.Collections.Hashtable.Add(System.Object, System.Object)
   at System.Collections.Specialized.HybridDictionary.Add(System.Object, System.Object)
   at Microsoft.VisualStudio.Utilities.PropertyCollection.AddProperty(System.Object, System.Object)
   at Codist.NaviBar.NaviBar..ctor(Microsoft.VisualStudio.Text.Editor.IWpfTextView)
   at Codist.NaviBar.CSharpBar..ctor(Microsoft.VisualStudio.Text.Editor.IWpfTextView)
   at Codist.NaviBar.NaviBarFactory+Overrider.AddNaviBar(System.Object, System.Windows.RoutedEventArgs)
   at Codist.NaviBar.NaviBarFactory+Overrider+<ResurrectNaviBar_OnUnloaded>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by wmjordan** [comment]
Please try the newer beta.

**Comment by fantasyz** [comment]
I have been coding for quite a while.  
Everything seems working right now. 
thanks

**Comment by wmjordan** [comment]
Good to hear that.
