### ISSUE TITLE
A few small issues

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#163]
Using latest Codist (from VS Marketplace that you released a few days ago):

1. I got VS 2019 16.11 P1 crash when clicking on a drop-down in the NaviBar:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at EnvDTE.ItemOperations.OpenFile(System.String, System.String)
   at Codist.TextEditorHelper.OpenFile(EnvDTE.DTE, System.String, System.Action`1<EnvDTE.Document>)
   at Codist.TextEditorHelper.OpenFile(EnvDTE.DTE, System.String, Int32, Int32)
   at Codist.CodeAnalysisHelper.GoToSource(Microsoft.CodeAnalysis.Location)
   at Codist.Controls.SymbolItem.GoToSource()
   at Codist.NaviBar.CSharpBar.MenuItemSelect(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   at System.Windows.UIElement.OnMouseUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

2. Testing out new C# 10 features I discovered that the braces `{ }` are not properly styled for `record struct { }` (a new thing in C# 10), but are properly styles for both `record { }` and `struct { }` (separately).

**Comment by wmjordan** [comment]
Problem 1 is terrible!

Did it occur to any items in the NaviBar, or some specific items?
Did it also occur when you clicked on the links in Super Quick Info either?

**Comment by fitdev** [comment]
> Did it occur to all items in the NaviBar, or some specific items?

No, it happened just once to me. I think it might be related to it using outdated info (i.e. file renamed, or refactoring performed), but I am not sure. Related to this I also noticed that after refactoring, NaviBar would sometimes display duplicates - both _old_ and _new_ versions (names) of the "same" type.

> Did it also occur when you clicked on the links in Super Quick Info either?

No, but I have not clicked there a lot.

This is the first time it happened to me and in general NaviBar works well (apart from being a bit slow to populate).

**Comment by wmjordan** [comment]
> it might be related to it using outdated info (i.e. file renamed, or refactoring performed)

Hmm, that might be the case.

> after refactoring

How did you refactor your code?

> an easy quick fix might be to try-catch the case when file is not found

This is reasonable.

**Comment by wmjordan** [comment]
> try-catch the case when file is not found

It is really weird.

There are lines of code which [checks whether the file exists](https://github.com/wmjordan/Codist/blob/fe73f2bf67d6192ebb4317c981d63e939473af95/Codist/Helpers/TextEditorHelper.cs#L451).

**Comment by fitdev** [comment]
> How did you refactor your code?

Oh, I do a lot of refactoring these days... Move classes to different namespaces, rename files, move to different folders. Mostly it is usually renaming types or methods.

> It is really weird.

Yeah, I agree. Well, maybe it was a one-ff thing. I will let you know if it happens again and try to note circumstances.

**Comment by wmjordan** [comment]
> Mostly it is usually renaming types or methods.

Please help writing the reproduction procedure that NaviBar is not working probably after refactoring code. I will look into it.
