### ISSUE TITLE
VS 2022 Crashed After Closing Symbol List

### ISSUE THREAD

**Issue by wmjordan** [wmjordan/Codist#183]
I know you are busy. But just wanted to let you know that latest Codist still crashes VS 2022 when it attempts to close floating member/type/location list popup.

![2021-10-28 14_36_39-DotNet - Microsoft Visual Studio Preview (Not Responding)](https://user-images.githubusercontent.com/8166847/139323368-9010395d-ab2d-44a6-8d28-b83814a3ae37.jpg)

For example, in this screenshot, I used NaviBar to click on the `Product6` which is a partial type defined in 2 source files. So it popped up a floating window/list with 2 file locations. When I clicked on one of the locations, VS crashed (the cause of the crash being this popup window closing):

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
   at System.Windows.Media.VisualCollection.get_Item(Int32)
   at System.Windows.Controls.UIElementCollection.get_Item(Int32)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.PrecomputeRecursive(System.Windows.Rect ByRef)
   at System.Windows.Media.Visual.Precompute()
   at System.Windows.Media.CompositionTarget.System.Windows.Media.ICompositionTarget.Render(Boolean, Channel)
   at System.Windows.Media.MediaContext.Render(System.Windows.Media.ICompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr, IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr, IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

```

_Originally posted by @fitdev in https://github.com/wmjordan/Codist/issues/169#issuecomment-954142595_

**Comment by wmjordan** [comment]
This is a tough problem which occurs occasionally.

**Comment by wmjordan** [comment]
@fitdev, I encountered this issue today, after switching to VS 2022. The same stack trace. Don't know how to fix it yet.

**Comment by fitdev** [comment]
At the moment I try not to use this feature for the fear of crashing entire VS. Though I do miss it - the functionality you added to find derived types / members for example is very useful!

**Comment by wmjordan** [comment]
I have only encountered one crash so far.

**Comment by fitdev** [comment]
I have not used this feature in the last few weeks for the fear of crashes and not wanting to reload all my work (in my case it takes ~3 minutes to get started all over), so I cannot provide feedback yet. They are likely to release a new preview version very soon, so we'll see how it behaves there.

**Comment by wmjordan** [comment]
There's a new version which attempts to address this issue.
Since it seldom occurs on my machine.
Please help test it on your side and tell me whether the problem is solved.
