### ISSUE TITLE
[BUG] Crash while i'm typing

### ISSUE THREAD

**Issue by SlimeNull** [wmjordan/Codist#269]
Here is the message in Windows Event Viewer
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
   at Microsoft.CodeAnalysis.SyntaxNode.FindNode(Microsoft.CodeAnalysis.Text.TextSpan, Boolean, Boolean)
   at Codist.Margins.CSharpMargin+SymbolReferenceMarker.Render(System.Windows.Media.DrawingContext)
   at Codist.Margins.CSharpMargin.OnRender(System.Windows.Media.DrawingContext)
   at System.Windows.UIElement.Arrange(System.Windows.Rect)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(System.Object)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

> I was typing a namespace like this, and it crashed before I finished typing.
> ```cs
> namespace ForeignKeyTest
> ```

**Comment by wmjordan** [comment]
> I was typing a namespace like this, and it crashed before I finished typing.

Your info helped a lot to fix this bug.
Please try the new beta and see whether it fixes the problem on your side.

**Comment by SlimeNull** [comment]
How to get the beta version?

**Comment by wmjordan** [comment]
请到此处下载：
https://github.com/wmjordan/Codist/issues/267

**Comment by SlimeNull** [comment]
好耶, beta 版本也会崩溃

**Comment by wmjordan** [comment]
崩溃后，系统日志里的堆栈跟踪消息是和上面一样的吗？

**Comment by wmjordan** [comment]
Codist 版本号是 7.4.0.8820 吗？

**Comment by wmjordan** [comment]
是否还能重现这个故障呢？
我用新版怎样也无法重现这个故障了。
如果遇到这个故障，还是在输入 namespace ＋名称空间 之后会崩溃吗？

**Comment by wmjordan** [comment]
是否还能重现这个故障呢？
如果遇到这个故障，还是在输入 namespace ＋名称空间 之后会崩溃吗？
我用新版怎样也无法重现这个故障了。最近发布的新版本增加了一些新功能，不妨也试用一下。

**Comment by SlimeNull** [comment]
我去试试吧, 总之我现在使用目前的beta版本还是有问题的.

**Comment by SlimeNull** [comment]
我又重新使用版本号为 7.4.0.8853 的 Codist 尝试复现故障, 崩溃并未发生. 你修复了些什么吗?

**Comment by wmjordan** [comment]
观察之前的代码，可能存在文档快照不匹配的问题。
当代码文本末端在变化的时候，就可能由于要检查的代码符号符号末端超出了文档快照的结尾，从而触发异常导致程序崩溃。
请再使用一段时间看看是否还会遇到这个问题。如果还遇到问题，请观察一下光标是否处于文档结尾。

**Comment by SlimeNull** [comment]
是的, 当时我就是清空了文件, 然后重新输入代码, 此时光标位于文件尾, 在输入的时候就出现了问题. 要不给它套一坨 try? 虽然不雅观, 但是很管用

**Comment by wmjordan** [comment]
先不套 try。
顶多做个长度判断就够了。
帮忙测试一下，看看是否能再现问题。如果问题不再现，就不用加代码了。
