### ISSUE TITLE
NullReferenceException in Codist 7.5.0.8912 and 7.6.0.9098

### ISSUE THREAD

**Issue by Bergam64** [wmjordan/Codist#289]
Hello,

I've discovered at least 2 cases of a `NullReferenceException` in Codist (both in v**7.5.0.8912** and v**7.6.0.9098**), which crashes VS 2022.

1) The first occurrence is in method `Codist.ToolTipHelper.ShowNamespaceSource`.  

    This bug happened at least in 2 distinct scenarios:
    - Right in the middle of a quick series of keyboard shortcuts, copying code between 2 C# documents. Unfortunately, I can't be more specific here.
    - I was displaying Super Quick Info for a method param of type enum and clicking on the enum namespace.

    Here's the relevant entry I've found each time in Event Viewer after each of the crashes:
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Codist.ToolTipHelper.ShowNamespaceSource(System.Windows.Controls.TextBlock, Microsoft.CodeAnalysis.INamespaceSymbol, Codist.SemanticContext)
   at Codist.ToolTipHelper.CreateToolTip(Microsoft.CodeAnalysis.ISymbol, Boolean, Codist.SemanticContext)
   at Codist.WpfHelper+InteractiveRun.OnToolTipOpening(System.Windows.Controls.ToolTipEventArgs)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.Controls.PopupControlService.RaiseToolTipOpeningEvent(Boolean)
   at System.Windows.Threading.DispatcherTimer.FireTick(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

2) The second one is in method `Codist.QuickInfo.QuickInfoOverrideController+QuickInfoPositioner.Reposition`.

    This happened while I was copying a multi-line selection in the left pane of a `*.md` file (I'm using VS extension "Markdown Editor v2" v2.0.132)

    Here's the relevant entry from Event Viewer:
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Codist.QuickInfo.QuickInfoOverrideController+QuickInfoPositioner.Reposition(Boolean)
   at Codist.QuickInfo.QuickInfoOverrideController.Session_StateChanged(System.Object, Microsoft.VisualStudio.Language.Intellisense.QuickInfoSessionStateChangedEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.TransitionTo(Microsoft.VisualStudio.Language.Intellisense.QuickInfoSessionState, Boolean)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoPresentationSession+<UpdatePresenterAsync>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoPresentationSession+<UpdateAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoBroker+<StartQuickInfoSessionAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoBroker+<TriggerQuickInfoAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LegacyQuickInfoSession+<<Start>b__46_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LegacyQuickInfoSession.Start()
   at Microsoft.VisualStudio.Editor.Implementation.ShimQuickInfoSource+<>c__DisplayClass11_0.<RetrySession>b__0(System.Object, System.EventArgs)
   at System.Windows.Threading.DispatcherTimer.FireTick(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

Please fix these bugs.

May I strongly suggest you to enable [**Nullable Reference Types**](https://learn.microsoft.com/en-us/dotnet/csharp/tutorials/nullable-reference-types) in your projects (if that's possible), as this will allow the C# compiler to detect potential null references upfront.

Thanks in advance.

**Comment by wmjordan** [comment]
Sorry to see that.
And thanks for the suggestion, I will see whether it is possible to turn on the Nullable Reference Types.

Please download the new beta (#288) and see whether the bug persists.

**Comment by Bergam64** [comment]
Hello,

Thanks for your quick fix.

Yesterday, I installed beta **7.6.0.9192**. So far, so good (no more `NullReferenceException`).

I'll let you know it this changes.

**Comment by wmjordan** [comment]
Thank you for your feedback.

9192 has a problem which disables the customization of advanced syntax highlight. Please download the newly uploaded beta which has fixed the problem.
