### ISSUE TITLE
VS Crash on CreateToolBar

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#29]
Using VS 2017 15.8.1 and Codist 3.05.0.1702:

When I navigate to source for `System.IO.FileInfo` (click Yes in VS to confirm decompiling sources), and then from the opened decompiled FileInfo document I then navigate to source of `System.IO.FileSystemEntry` I get a crash: NullReferenceException in Codist.dll:

```
 at Codist.CodeAnalysisHelper.GetDocument(Workspace workspace, SnapshotSpan span) in E:\Codes\Open Source Projects\Codist\Codist\Helpers\CodeAnalysisHelper.cs:line 26
 at Codist.SmartBars.CSharpSmartBar.UpdateSemanticModel() in E:\Codes\Open Source Projects\Codist\Codist\SmartBars\CSharpSmartBar.cs:line 0
 at Codist.SmartBars.CSharpSmartBar.AddCommands() in E:\Codes\Open Source Projects\Codist\Codist\SmartBars\CSharpSmartBar.cs:line 34
 at Codist.SmartBars.SmartBar.CreateToolBar(Object dummy) in E:\Codes\Open Source Projects\Codist\Codist\SmartBars\SmartBar.cs:line 159
 at Codist.SmartBars.SmartBar.<CreateToolBar>b__26_0() in E:\Codes\Open Source Projects\Codist\Codist\SmartBars\SmartBar.cs:line 145
 at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
 at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
 at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
 at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
 at System.Windows.Threading.Dispatcher.Invoke(Action callback)
 at Codist.SmartBars.SmartBar.CreateToolBar(Object dummy) in E:\Codes\Open Source Projects\Codist\Codist\SmartBars\SmartBar.cs:line 145
 at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
 at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
 at System.Threading.TimerQueueTimer.CallCallback()
 at System.Threading.TimerQueueTimer.Fire()
 at System.Threading.TimerQueue.FireNextTimers()
 at System.Threading.TimerQueue.AppDomainTimerCallback()
```

**Comment by wmjordan** [comment]
OK, that bug came again. Could you please checkout the corresponding System Events entry in the Windows Event Viewer?

**Comment by fitdev** [comment]
Here are the details from the event log:

```
Application: devenv.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.ArgumentNullException at Codist.CodeAnalysisHelper.GetDocument(Microsoft.CodeAnalysis.Workspace, Microsoft.VisualStudio.Text.SnapshotSpan) at Codist.SmartBars.CSharpSmartBar.UpdateSemanticModel() at Codist.SmartBars.CSharpSmartBar.AddCommands() at Codist.SmartBars.SmartBar.CreateToolBar(System.Object) at Codist.SmartBars.SmartBar.<CreateToolBar>b__26_0() at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore() at System.Windows.Threading.DispatcherOperation.InvokeImpl() at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) at System.Windows.Threading.DispatcherOperation.Wait(System.TimeSpan) at System.Windows.Threading.Dispatcher.InvokeImpl(System.Windows.Threading.DispatcherOperation, System.Threading.CancellationToken, System.TimeSpan) at System.Windows.Threading.Dispatcher.Invoke(System.Action, System.Windows.Threading.DispatcherPriority, System.Threading.CancellationToken, System.TimeSpan) at System.Windows.Threading.Dispatcher.Invoke(System.Action) at Codist.SmartBars.SmartBar.CreateToolBar(System.Object) at System.Threading.TimerQueueTimer.CallCallbackInContext(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.TimerQueueTimer.CallCallback() at System.Threading.TimerQueueTimer.Fire() at System.Threading.TimerQueue.FireNextTimers() at System.Threading.TimerQueue.AppDomainTimerCallback() 
```

**Comment by fitdev** [comment]
Using v. 3.7.0.1862, once again got VS crash when navigating through decompiled sources (the recently added VS feature that lets you see .Net Framework sources right inside of VS):

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Codist.SmartBars.CSharpSmartBar.UpdateSemanticModel()
   at Codist.SmartBars.CSharpSmartBar.AddCommands()
   at Codist.SmartBars.SmartBar.CreateToolBar()
   at Codist.SmartBars.SmartBar.CreateToolBar(System.Object)
   at Codist.SmartBars.SmartBar.<CreateToolBar>b__26_0()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Windows.Threading.DispatcherOperation.Wait(System.TimeSpan)
   at System.Windows.Threading.Dispatcher.InvokeImpl(System.Windows.Threading.DispatcherOperation, System.Threading.CancellationToken, System.TimeSpan)
   at System.Windows.Threading.Dispatcher.Invoke(System.Action, System.Windows.Threading.DispatcherPriority, System.Threading.CancellationToken, System.TimeSpan)
   at System.Windows.Threading.Dispatcher.Invoke(System.Action)
   at Codist.SmartBars.SmartBar.CreateToolBar(System.Object)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()

```

**Comment by wmjordan** [comment]
It is so weird. I've never encountered this issue, but it occurred to you so frequently.
I'll try to catch this in the next release.
