### ISSUE TITLE
Unable to cast object of type ContainerElement to type ClassifiedTextElement

### ISSUE THREAD

**Issue by Stekeblad** [wmjordan/Codist#298]
I got a popup with the below error message when editing a[ .http](https://devblogs.microsoft.com/visualstudio/visual-studio-2022-17-5-released/#api) (rest client requests) file. I don't know what I did and have tried to recreate the exception without success.

Codist 7.7.1.9318
Visual Studio 17.8 - Preview 1

```
System.InvalidCastException: Unable to cast object of type 'Microsoft.VisualStudio.Text.Adornments.ContainerElement' to type 'Microsoft.VisualStudio.Text.Adornments.ClassifiedTextElement'.
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at Codist.QuickInfo.QuickInfoOverride.ErrorTags.GetTags(ITagAggregator`1 tagger, SnapshotSpan span) in D:\Codes\Open Source Projects\Codist\Codist\QuickInfo\QuickInfoOverride.cs:line 766
   at Codist.QuickInfo.QuickInfoOverride.ErrorTags.GetErrorIcon(String code, ITagAggregator`1 tagger, SnapshotSpan span) in D:\Codes\Open Source Projects\Codist\Codist\QuickInfo\QuickInfoOverride.cs:line 722
   at Codist.QuickInfo.QuickInfoOverride.DefaultOverride.GetIconForErrorText(TextBlock textBlock) in D:\Codes\Open Source Projects\Codist\Codist\QuickInfo\QuickInfoOverride.cs:line 358
   at Codist.QuickInfo.QuickInfoOverride.UIOverride.OverrideTextBlock(TextBlock t) in D:\Codes\Open Source Projects\Codist\Codist\QuickInfo\QuickInfoOverride.cs:line 689
   at Codist.QuickInfo.QuickInfoOverride.UIOverride.MakeTextualContentSelectableWithIcon(Panel p) in D:\Codes\Open Source Projects\Codist\Codist\QuickInfo\QuickInfoOverride.cs:line 474
   at Codist.QuickInfo.QuickInfoOverride.UIOverride.OnVisualParentChanged(DependencyObject oldParent) in D:\Codes\Open Source Projects\Codist\Codist\QuickInfo\QuickInfoOverride.cs:line 420
```

**Comment by wmjordan** [comment]
Thank you for reporting the bug.
I've uploaded a new release to fix this problem.
Please download it from the marketplace or the release page here.
