### ISSUE TITLE
Codist crashes VS when mouse hovers over the namespace part of the QuickInfo

### ISSUE THREAD

**Issue by Bergam64** [wmjordan/Codist#307]
Dear Codist team,

An old bug (a `NullReferenceException` that crashes VS, which I already reported in issue #289) is still present in the latest version (**7.7.2.9370**).

Repro:
- Open a solution with at least 1 C# file.
- Find anything with type string.
- Hover over the `string` type. QuickInfo appears:
  ![image](https://github.com/wmjordan/Codist/assets/29800159/f28b312a-ebef-4fee-ab0a-7dd9ceb6a96e)
  So far so good.
- Now hover over the namespace part at the bottom (see red highlight).
- At this point, VS become unresponsive. In fact, it is crashing (it takes a moment).
- VS auto-restarts and auto-reopens the previous solution, with this message at the top:
  ![image](https://github.com/wmjordan/Codist/assets/29800159/49b64223-c15d-4969-896b-34146d274ffb)
- At this point, if you look in Event Viewer (at the OS level), you can see the following entry in the `Windows Log -> Application`:
  ```csharp
  Application: devenv.exe
  Framework Version: v4.0.30319
  Description: The process was terminated due to an unhandled exception.
  Exception Info: System.NullReferenceException
     at Codist.ToolTipHelper.ShowNamespaceSource(System.Windows.Controls.TextBlock, Microsoft.CodeAnalysis.INamespaceSymbol, Codist.SemanticContext)
     at Codist.ToolTipHelper.CreateToolTip(Microsoft.CodeAnalysis.ISymbol, Boolean, Codist.SemanticContext)
     at Codist.WpfHelper+InteractiveRun.OnToolTipOpening(System.Windows.Controls.ToolTipEventArgs)
     at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
     at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
     at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
     at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
     at System.Windows.Controls.PopupControlService.RaiseToolTipOpeningEvent(Boolean)
     at System.Windows.Threading.DispatcherTimer.FireTick(System.Object)
     at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
     at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
     at System.Windows.Threading.DispatcherOperation.InvokeImpl()
     at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
     at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
     at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
     at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
     at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
     at System.Windows.Threading.DispatcherOperation.Invoke()
     at System.Windows.Threading.Dispatcher.ProcessQueue()
     at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
     at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
     at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
     at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
     at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
     at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
     at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
  ```
  
It is clear that you definitely have a serious problem in method `Codist.ToolTipHelper.ShowNamespaceSource`.

Please fix this ASAP, since this is a real productivity killer. Each time QuickInfo is display and I accidently move my mouse over the Namespace part, VS crashes.

Thanks in advance.

**Comment by wmjordan** [comment]
Hi, I am sorry that I can not reproduce this issue. It is good at my side.
<img width="310" alt="image" src="https://github.com/wmjordan/Codist/assets/12182730/8dc34347-26c5-4fec-9735-ae12d5c8f6f7">

Could you send a solution with a C# file for me to test?

If this issue persists, please uncheck the "_Containing namespace and assembly_" check box in the _Codist/Super Quick Info_ options page. So, the namespaces and assemblies won't show up on Quick Info.

**Comment by wmjordan** [comment]
BTW, what's the version of your VS?

**Comment by Bergam64** [comment]
Hello,

I've created a very simple solution that reproduces the bug (this time involving type `int` instead of `string`):
[CodistNullRefInQuickInfoNamespace.zip](https://github.com/wmjordan/Codist/files/13610704/CodistNullRefInQuickInfoNamespace.zip)

Repro:
- Open solution.
- Open class `Class1`.
- Follow these instructions:
  ![image](https://github.com/wmjordan/Codist/assets/29800159/0d7a1067-4508-4d47-99e7-019e9da68b1c)

I'm using Visual Studio 2022 Professional v**17.8.2**.

The following info may also be useful:
![image](https://github.com/wmjordan/Codist/assets/29800159/c9278754-db01-4931-83cf-b0761c2d52e9)

![image](https://github.com/wmjordan/Codist/assets/29800159/99129a01-5c1c-4181-bd16-164761ddc20d)

![image](https://github.com/wmjordan/Codist/assets/29800159/252f80a9-61c2-4618-be14-a929ed378c1c)

And finally:
> If this issue persists, please uncheck the "Containing namespace and assembly" check box in the Codist/Super Quick Info options page. So, the namespaces and assemblies won't show up on Quick Info.

I'd rather not, as the Namespace information is very useful.

I hope that'll be enough for you to repro the bug. If not, feel free to ask me more info.

**Comment by wmjordan** [comment]
Thank you for replying.
It is still working perfectly on my computer.
I am using the latest preview version of VS.
17.8.2 should be fine.

Perhaps I shall make a debug version for you to test what's going wrong.

<img width="310" alt="image" src="https://github.com/wmjordan/Codist/assets/12182730/1aaeac5b-6e74-4155-add9-827c8ed983c7">

**Comment by Bergam64** [comment]
Hello,

A debug version would likely add line numbers to the stack trace. That's a step forward, but will that be enough for you to investigate ?

Have you tried enabling the [nullable reference types](https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references) feature of C# 8 in your project? That's a really good tool to detect potential `NullReferenceException`s upfront in the code.

In the meantime, here's my config file, in case it would turn out to be useful.
[Config.json](https://github.com/wmjordan/Codist/files/13644778/Config.json)

Best regards.

**Comment by wmjordan** [comment]
Please download and install this version.
It should display an error box when something goes null in that function.
[Codist.zip](https://github.com/wmjordan/Codist/files/13645758/Codist.zip)

**Comment by wmjordan** [comment]
Could you please take the trouble of posting the stack trace in the Windows Event Viewer?

**Comment by Bergam64** [comment]
I initially intended to, but it's _**exactly**_ the same one as the one in my initial post, so I didn't.

And unfortunately, even in v**7.7.2.9410**, line numbers are still not available in stack traces.
I don't know why, since file `Codist.pdb` _is_ part of your VSIX.

What else can I do to help you?

**Comment by wmjordan** [comment]
Hi, sorry to see this.
Please use this debug version.
[Codist.zip](https://github.com/wmjordan/Codist/files/13669673/Codist.zip)

**Comment by Bergam64** [comment]
Hi.

I've installed your latest version (**7.7.2.9432**). Here's what I've discovered:
- If I use the solution I uploaded a few days ago in this discussion (**CodistNullRefInQuickInfoNamespace**), I now get this when I hover over the `bool` keyword then on the Namespace part:
  ![image](https://github.com/wmjordan/Codist/assets/29800159/a0b4b234-a4b1-4be4-91d0-1b029382f12c)
  and, of course, VS no longer crashes, which is already a significant step forward for me.
- I've also tried in another (huge) solution. Same outcome.
- For the record, I've done 2 attempts each time:
  - one right after opening the solution (i.e. while some VS background tasks are still running):
    ![image](https://github.com/wmjordan/Codist/assets/29800159/1658687a-e098-4ec1-823a-162465595aca)
  - and another one, when all VS background tasks are done running:
    ![image](https://github.com/wmjordan/Codist/assets/29800159/6d3599c2-527d-4899-bae2-cae57780b5f8)


  The outcome is the same in all cases.

Good hunting !

**Comment by wmjordan** [comment]
I managed to reproduce your issue with your provided config.json file.
This bug should be fixed with the following version.
[Codist.zip](https://github.com/wmjordan/Codist/files/13692702/Codist.zip)

**Comment by Bergam64** [comment]
Hi !

I've just installed your latest version (v**7.7.2.9433**) and it seems you've finally nailed this bug:
![image](https://github.com/wmjordan/Codist/assets/29800159/39e8cfd3-4346-4196-aaca-75a9c428ea62)

Thanks!

Please do publish this version thru the normal channels, so all users can get it.

BTW, I couldn't find documentation about this namespace tooltip [anywhere here](https://github.com/wmjordan/Codist?tab=readme-ov-file#super-quick-info).
I wonder what's the meaning of the **Location** property, which displays an `int`?

Thanks in advance.

**Comment by wmjordan** [comment]
The Location is a counter where the namespace appears in the source code.
