### ISSUE TITLE
System.NullReferenceException when opening a file (multiple times, i use the disable checkbox)

### ISSUE THREAD

**Issue by LaggAt** [wmjordan/Codist#332]
Hi, I get this information:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Codist.SmartBars.CSharpSmartBar.<AddCommandsAsync>d__10.MoveNext() in D:\Codes\Open Source Projects\Codist\Codist\SmartBars\CSharpSmartBar.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Codist.SmartBars.SmartBar.<InternalCreateToolBarAsync>d__73.MoveNext() in D:\Codes\Open Source Projects\Codist\Codist\SmartBars\SmartBar.cs:line 189

Could someone look into it? Thanks.

**Comment by wmjordan** [comment]
Hi, does this issue occur frequently?

**Comment by wmjordan** [comment]
Please try the following new beta and see whether the issue reoccurs.
[Codist.zip](https://github.com/user-attachments/files/16646972/Codist.zip)

**Comment by LaggAt** [comment]
> Please try the following new beta and see whether the issue reoccurs. [Codist.zip](https://github.com/user-attachments/files/16646972/Codist.zip)

Hi, thanks. This seems to fix it. 
Also the SmartBar is working (which I didn't test before, so maybe it was working all the time). 

I somehow got the errors once more after updating. As I cannot reproduce this anymore I think I am wrong here and somehow started the previous version.

So thanks, I confirm the fix working.
