### ISSUE TITLE
VS Crash when setting conditional breakpoint & some small issues

### ISSUE THREAD

**Issue by fitdev** [wmjordan/Codist#90]
Using latest beta version of Codist, VS Crashes after I click on "Close" button when setting conditional breakpoint:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Codist.Margins.CommentMargin.Dispose(Boolean)
   at Codist.Margins.CommentMargin.Dispose()
   at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.DisposeMargin(Microsoft.VisualStudio.Text.Editor.IWpfTextViewMargin)
   at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.Close()
   at Microsoft.VisualStudio.Text.OverviewMargin.Implementation.EnhancedScrollBarContainerMargin.Close()
   at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.Dispose()
   at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.DisposeMargin(Microsoft.VisualStudio.Text.Editor.IWpfTextViewMargin)
   at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.Close()
   at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.Dispose()
   at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.DisposeMargin(Microsoft.VisualStudio.Text.Editor.IWpfTextViewMargin)
   at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.Close()
   at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.Dispose()
   at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.DisposeMargin(Microsoft.VisualStudio.Text.Editor.IWpfTextViewMargin)
   at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.Close()
   at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.Dispose()
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextViewHost.Close()
```

**Comment by fitdev** [comment]
Another tiny bug - improper parenthesis colorization when casting to `Sometype[]`:

![2019-06-20 14_38_55-DotNet - Microsoft Visual Studio Preview](https://user-images.githubusercontent.com/8166847/59846814-885a9e00-9369-11e9-94da-bbe095a0eac1.jpg)

**Comment by fitdev** [comment]
Oh, and one more small thing: in Quick Info tooltips, documentation comments only work for single-level `<inheritdoc/>`s. For more than one level no documentation comment is shown (i.e. in the interface -> abatract base class -> concrete class hierarchy, member with documentation defined in the interface is not going to show `<inheritdoc/>`-ed comment for the overridden member in the concrete class).

**Comment by wmjordan** [comment]
Please try this new beta:
[Codist.zip](https://github.com/wmjordan/Codist/files/3312511/Codist.zip)

**Comment by fitdev** [comment]
Thank you for your quick fixes. Issues 1 and 2 are fixed, however the issue with `<inheritdoc/>` remains:

```
  public interface IInterface {
    /// <summary>
    /// Actual doc comment
    /// </summary>
    string Method(object? value);
  }
  public abstract class BaseClass : IInterface {
    ///<inheritdoc/>
    public abstract string Method(object? value); //<-- doc comment is displayed correctly
  }
  public class ConcreteClass : BaseClass {
    ///<inheritdoc/>
    public override string Method(object? value); //<-- doc comment is NOT displayed
  }
```

**Comment by wmjordan** [comment]
Could you try remove those "?" marks behind the `object` type and try again?

**Comment by wmjordan** [comment]
It is unexpected that the `<inheritdoc/>` prevented the doc to be inherited--the XML doc inheritance is automatic in Codist, you can remove `<inheritdoc/>` tags without `cref` attributes.

**Comment by wmjordan** [comment]
Please try this new beta:
[Codist.zip](https://github.com/wmjordan/Codist/files/3313523/Codist.zip)

**Comment by fitdev** [comment]
Thank you! Now this has been fixed in the latest version!
